/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import Proyecto.Admin;
import Proyecto.Cola;
import Proyecto.IA;
import Proyecto.Nodo;
import Proyecto.Personajes;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.concurrent.Semaphore;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author soyis
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        setLocationRelativeTo(null);
        
    }
    
    public void setImageLabel(JLabel nombrelabel, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(nombrelabel.getWidth(), nombrelabel.getHeight(), nombrelabel.getWidth()));
        nombrelabel.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloLabel = new javax.swing.JLabel();
        StarwarsLabel = new javax.swing.JLabel();
        StartreckLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        VsLabel = new javax.swing.JLabel();
        BattleDuration = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        RefuerzosPane = new javax.swing.JScrollPane();
        RefuerzosSW = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        RefuerzosST = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        Prioridad2SW = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        Prioridad3SW = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        Prioridad1SW1 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        Prioridad1ST1 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        Prioridad2ST = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        Prioridad3ST1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        FondoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloLabel.setFont(new java.awt.Font("Felix Titling", 1, 36)); // NOI18N
        TituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        TituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloLabel.setText("Pelea de Sagas");
        getContentPane().add(TituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1190, 40));

        StarwarsLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\soyis\\OneDrive\\Escritorio\\COLLEGE\\Sistemas operativos\\Proyecto 2\\Proyecto2-SO\\Proyecto2SO\\src\\Images\\LogoStarWars2.png")); // NOI18N
        getContentPane().add(StarwarsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 140, 80));

        StartreckLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\soyis\\OneDrive\\Escritorio\\COLLEGE\\Sistemas operativos\\Proyecto 2\\Proyecto2-SO\\Proyecto2SO\\src\\Images\\LogoStarTreck.png")); // NOI18N
        getContentPane().add(StartreckLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 110, 150, 70));

        jLabel1.setFont(new java.awt.Font("Coco Gothic Heavy", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Score: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Coco Gothic Heavy", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Estado de la IA: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 620, -1, -1));

        VsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VsLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\soyis\\OneDrive\\Escritorio\\COLLEGE\\Sistemas operativos\\Proyecto 2\\Proyecto2-SO\\Proyecto2SO\\src\\Images\\VS.png")); // NOI18N
        getContentPane().add(VsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 140, 90));

        BattleDuration.setBackground(new java.awt.Color(102, 102, 102));
        BattleDuration.setForeground(new java.awt.Color(255, 255, 255));
        BattleDuration.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BattleDuration.setText("10");
        getContentPane().add(BattleDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, 70, 30));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Battle Duration");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 560, 130, 30));

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Refuerzos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 490, -1, -1));

        RefuerzosSW.setEditable(false);
        RefuerzosSW.setBackground(new java.awt.Color(51, 51, 51));
        RefuerzosSW.setColumns(20);
        RefuerzosSW.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        RefuerzosSW.setForeground(new java.awt.Color(255, 255, 255));
        RefuerzosSW.setRows(5);
        RefuerzosSW.setToolTipText("");
        RefuerzosPane.setViewportView(RefuerzosSW);

        getContentPane().add(RefuerzosPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 270, 50));

        RefuerzosST.setEditable(false);
        RefuerzosST.setBackground(new java.awt.Color(51, 51, 51));
        RefuerzosST.setColumns(20);
        RefuerzosST.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        RefuerzosST.setForeground(new java.awt.Color(255, 255, 255));
        RefuerzosST.setRows(5);
        RefuerzosST.setToolTipText("");
        jScrollPane4.setViewportView(RefuerzosST);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 520, 270, 50));

        Prioridad2SW.setEditable(false);
        Prioridad2SW.setBackground(new java.awt.Color(51, 51, 51));
        Prioridad2SW.setColumns(20);
        Prioridad2SW.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        Prioridad2SW.setForeground(new java.awt.Color(255, 255, 255));
        Prioridad2SW.setRows(5);
        Prioridad2SW.setToolTipText("");
        jScrollPane5.setViewportView(Prioridad2SW);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 270, 50));

        Prioridad3SW.setEditable(false);
        Prioridad3SW.setBackground(new java.awt.Color(51, 51, 51));
        Prioridad3SW.setColumns(20);
        Prioridad3SW.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        Prioridad3SW.setForeground(new java.awt.Color(255, 255, 255));
        Prioridad3SW.setRows(5);
        Prioridad3SW.setToolTipText("");
        jScrollPane6.setViewportView(Prioridad3SW);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 270, 50));

        Prioridad1SW1.setEditable(false);
        Prioridad1SW1.setBackground(new java.awt.Color(51, 51, 51));
        Prioridad1SW1.setColumns(20);
        Prioridad1SW1.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        Prioridad1SW1.setForeground(new java.awt.Color(255, 255, 255));
        Prioridad1SW1.setRows(5);
        Prioridad1SW1.setToolTipText("");
        jScrollPane7.setViewportView(Prioridad1SW1);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 270, 50));

        Prioridad1ST1.setEditable(false);
        Prioridad1ST1.setBackground(new java.awt.Color(51, 51, 51));
        Prioridad1ST1.setColumns(20);
        Prioridad1ST1.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        Prioridad1ST1.setForeground(new java.awt.Color(255, 255, 255));
        Prioridad1ST1.setRows(5);
        Prioridad1ST1.setToolTipText("");
        jScrollPane8.setViewportView(Prioridad1ST1);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, 270, 50));

        Prioridad2ST.setEditable(false);
        Prioridad2ST.setBackground(new java.awt.Color(51, 51, 51));
        Prioridad2ST.setColumns(20);
        Prioridad2ST.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        Prioridad2ST.setForeground(new java.awt.Color(255, 255, 255));
        Prioridad2ST.setRows(5);
        Prioridad2ST.setToolTipText("");
        jScrollPane9.setViewportView(Prioridad2ST);

        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 340, 270, 50));

        Prioridad3ST1.setEditable(false);
        Prioridad3ST1.setBackground(new java.awt.Color(51, 51, 51));
        Prioridad3ST1.setColumns(20);
        Prioridad3ST1.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        Prioridad3ST1.setForeground(new java.awt.Color(255, 255, 255));
        Prioridad3ST1.setRows(5);
        Prioridad3ST1.setToolTipText("");
        jScrollPane10.setViewportView(Prioridad3ST1);

        getContentPane().add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 430, 270, 50));

        jLabel4.setFont(new java.awt.Font("Coco Gothic Heavy", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Score: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Prioridad 1");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Prioridad 1");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Prioridad 2");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Prioridad 3");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Prioridad 2");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Prioridad 3");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Refuerzos");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        jLabel12.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ID: ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, -1, -1));

        jLabel13.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("HabiLIDAD: ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, -1, 20));

        jLabel15.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Puntos de vida:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, -1, 20));

        jLabel14.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ID: ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jLabel16.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("HabiLIDAD: ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, 20));

        jLabel17.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("agilidad:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, -1, 20));

        jLabel18.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Puntos de vida:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, -1, 20));

        jLabel19.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Fuerza:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, -1, 20));

        jLabel20.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Fuerza:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, -1, 20));

        jLabel21.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("agilidad:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, -1, 20));

        FondoLabel.setFont(new java.awt.Font("Felix Titling", 0, 36)); // NOI18N
        FondoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\soyis\\OneDrive\\Escritorio\\COLLEGE\\Sistemas operativos\\Proyecto 2\\Proyecto2-SO\\Proyecto2SO\\src\\Images\\Fondo.jpg")); // NOI18N
        FondoLabel.setText("Pelea de Sagas");
        getContentPane().add(FondoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1209, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BattleDuration;
    private javax.swing.JLabel FondoLabel;
    private javax.swing.JTextArea Prioridad1ST1;
    private javax.swing.JTextArea Prioridad1SW1;
    private javax.swing.JTextArea Prioridad2ST;
    private javax.swing.JTextArea Prioridad2SW;
    private javax.swing.JTextArea Prioridad3ST1;
    private javax.swing.JTextArea Prioridad3SW;
    private javax.swing.JScrollPane RefuerzosPane;
    private javax.swing.JTextArea RefuerzosST;
    private javax.swing.JTextArea RefuerzosSW;
    private javax.swing.JLabel StartreckLabel;
    private javax.swing.JLabel StarwarsLabel;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JLabel VsLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables

 
}
